### ISSUE TITLE
Higher node.js versions

### ISSUE THREAD

**Issue by rahejova** [hobbyquaker/influx4mqtt#2]
It works with node.js 6.x, but not with 8.x or 9.x:

$ sudo npm install -g influx4mqtt 

results in:

npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/hobbyquaker/node-influx.git /root/.npm/_cacache/tmp/git-clone-18157aae
npm ERR! fatal: Konnte führende Verzeichnisse von '/root/.npm/_cacache/tmp/git-clone-18157aae' nicht erstellen.: Keine Berechtigung
npm ERR!

for 8.x and 9.x (6.x ok)

**Comment by hobbyquaker** [comment]
released v1.0.0, should work now. Mind that there are new command line params, see readme

**Comment by rahejova** [comment]
Tested with node.js 8.9.4 and 9.5.0. It seems to work. Many thanks for the fast change.
